PATCH {{host}}/admin_api/user
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json

{
  "user_name":  "test",
  "coupons": "1"
}

###

GET {{host}}/admin_api/user
Authorization: Basic {{user}} {{pass}}

###

GET {{host}}/api/list_for_day.csv?date_of_day=2020-03-26
Authorization: Basic {{user}} {{pass}}

###

DELETE {{host}}/api/claim_token?claim_token=ySKhTgyNdrUqKksaCXyrcMBJDLjkWdkN
Authorization: Basic {{user}} {{pass}}
Accept: application/json

###
POST {{host}}/api/book_appointment
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json

{
  "claim_token":  "OooMeGCSYjLsrdAqVLfjnFbMbFsZIiPm",
  "office":  "Musterbehörde",
  "first_name":  "Max",
  "name":  "Mustermann",
  "phone":  "012/0123456",
  "start_date_time": "2020-04-14T12:00:00"
}

###
GET {{host}}/api/claim_appointment?start_date_time=2020-04-14T12:00:00
Authorization: Basic {{user}} {{pass}}
Accept: application/json

###
GET {{host}}/api/next_free_slots
Authorization: Basic {{user}} {{pass}}
Accept: application/json

###
GET {{host}}/healthcheck
Accept: application/json

####