PATCH http://localhost:8000/admin_api/user
Content-Type: application/json

{
  "user_name":  "test",
  "coupons": "1"
}

###

GET http://localhost:8000/admin_api/user

###

GET http://localhost:8000/api/list_for_day.csv?date_of_day=2020-04-20

###

DELETE http://localhost:8000/api/claim_token?claim_token=ySKhTgyNdrUqKksaCXyrcMBJDLjkWdkN
Accept: application/json

###
POST http://localhost:8000/api/book_appointment
Content-Type: application/json

{
  "claim_token":  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "office":  "Musterbehörde",
  "first_name":  "Max",
  "name":  "Mustermann",
  "phone":  "012/0123456",
  "start_date_time": "2020-04-20T04:20:00+00:00"
}

###
GET http://localhost:8000/api/claim_appointment?start_date_time=2020-04-20T04:20:00
Accept: application/json

###
GET http://localhost:8000/api/next_free_slots
Accept: application/json

###
GET http://localhost:8000/healthcheck
Accept: application/json

####